# Generated by Django 6.0.2 on 2026-03-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueentry',
            old_name='joined_at',
            new_name='created_at',
        ),
    ]
